# Generated by Django 6.0.5 on 2026-05-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_project_owner_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='task_attachments/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='task_images/%Y/%m/%d/'),
        ),
    ]
